name: Release new version of package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release. Must be a valid version number; x is forbidden'
        required: true
        default: '0.1.x'
      test:
        description: 'Release beta release to test PyPI'
        required: true
        type: boolean
        default: true

jobs:
  create_release_pr:
    name: Create release PR
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/hirundo
    permissions:
      contents: write  # Used to push branch with release
      pull-requests: write  # Used to create and merge PR with release
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.10"
          activate-environment: true

      - name: Bump version with `bumpver` then push tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          uv sync --group dev
          source .venv/bin/activate
          git config user.name "GitHub Actions [release-bot]"
          git config user.email "github-actions@hirundo.io"
          git checkout -b release-${{ github.event.inputs.version }}
          bumpver update --set-version ${{ github.event.inputs.version }}
          uv lock
          git commit -am "Bump version to ${{ github.event.inputs.version }}"
          git push -u origin release-${{ github.event.inputs.version }}
          gh pr create -a ${{ github.event.sender.login || github.actor }} --title "v${{ github.event.inputs.version }}" \
            --body "" --label "${{ github.event.inputs.test == 'true' && 'test' || 'release' }}"
